DROP SCHEMA IF EXISTS `news` ;
CREATE SCHEMA IF NOT EXISTS `news` DEFAULT CHARACTER SET utf8 ;
USE `news`;

CREATE TABLE `news`.`news_items` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `origin` BIGINT(64) NOT NULL,
  `title` VARCHAR(128) NOT NULL,
  `text` BLOB NOT NULL,
  PRIMARY KEY (`id`));